# Generated by Django 5.2.8 on 2025-11-25 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droguerias', '0001_initial'),
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='drogueria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='droguerias.drogueria'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='drogueria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='droguerias.drogueria'),
        ),
    ]
