# Generated by Django 5.2.8 on 2025-11-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_medicamento_drogueria_movimientoinventario_drogueria'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='costo_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='lote',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='stock_reservado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
