# Generated by Django 5.2.8 on 2025-11-25 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droguerias', '0001_initial'),
        ('inventario', '0004_medicamento_codigo_barra_medicamento_costo_compra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='medicamento',
            constraint=models.UniqueConstraint(fields=('nombre', 'drogueria'), name='unique_nombre_drogueria'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_destino', to='droguerias.drogueria'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='medicamento_destino',
            field=models.ForeignKey(blank=True, help_text='Puede apuntar a la entrada equivalente en la droguería destino (si existe)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_destino', to='inventario.medicamento'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='medicamento_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_origen', to='inventario.medicamento'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_origen', to='droguerias.drogueria'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='respondedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_prestamo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
