# Generated by Django 5.2.8 on 2025-11-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droguerias', '0001_initial'),
        ('inventario', '0005_prestamo_alter_medicamento_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('low_stock', 'Stock bajo'), ('vencido', 'Vencido'), ('prestamo', 'Prestamo'), ('info', 'Información')], max_length=30)),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='warning', max_length=10)),
                ('mensaje', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('drogueria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='droguerias.drogueria')),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='inventario.medicamento')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
